// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://twzouhckgqolxffbwteu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR3em91aGNrZ3FvbHhmZmJ3dGV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzMDIwMDIsImV4cCI6MjA3Mzg3ODAwMn0.jXBn7dbBHKUW8oKICznN7uG-7TaPRQn0eq6hx5uwjO0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});